[[language]]
name = "python"
language-servers = [ "basedpyright" ]

# Install ruff-lsp
# [language-server.ruff]
#   command = "ruff-lsp"

# Install: pyright
[language-server.basedpyright]
command = "basedpyright-langserver"

[language-server.basedpyright.config.basedpyright.analysis]
typeCheckingMode = "off"

[language-server.basedpyright.config.basedpyright.analysis.diagnosticSeverityOverrides]
# reportMissingImports = false
# reportMissingTypeStubs = false
# reportUntypedFunctionDecorator = false

# Covered by ruff
# reportUnusedImport = false

reportUnknownParameterType = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportMissingParameterType = false
